FROM python:3.10-slim

WORKDIR /app

# Copy universal server
COPY ./server/server.py /app/server.py

# Copy function code
COPY ./handlers/{handler}.py /app/main.py   

# Install dependencies
COPY ./handlers/{handler}_requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy all dependency files from deps folder
COPY ./deps/* /app/

EXPOSE 8080
CMD ["python", "server.py"]
