apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: knative-timestamp-filter
  namespace: istio-system
  labels:
    app: knative-faas
    type: faas-dns-timestamp
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: ROUTE_CONFIGURATION
      patch:
        operation: MERGE
        value:
          request_headers_to_add:
            - header:
                key: "x-request-start-time"
                # Inject the request start time in nanoseconds since epoch
                value: "%START_TIME(%s%9f)%"
              append: false
