clusterName: "elasticsearch"

nodeGroup: "master"

# image:
#   tag: 5.6.4_1
  
replicas: 3

roles:
  - master
  - ingest
  - data

esJavaOpts: "-Xmx2g -Xms2g"

resources:
  requests:
    cpu: "1000m"
    memory: "5Gi"
  limits:
    cpu: "1000m"
    memory: "5Gi"

secret:
  enabled: true
  password: "admin" # generated randomly if not defined

# Hard means that by default pods will only be scheduled if there are enough nodes for them
# and that they will never end up on the same node. Setting this to soft will do this "best effort"
antiAffinity: "soft"

# This is the node affinity settings as defined in
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
nodeAffinity: 
preferredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - knative
        - knative-m02
        - knative-m03

