mode: daemonset

image:
  repository: otel/opentelemetry-collector-k8s

presets:
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true

config:
  exporters:
    debug: {}
  extensions:
    # The health_check extension is mandatory for this chart.
    # Without the health_check extension the collector will fail the readiness and liveliness probes.
    # The health_check extension can be modified, but should never be removed.
    health_check:
      endpoint: 0.0.0.0:13133
  processors:
    batch: {}
    # Default memory limiter configuration for the collector based on k8s resource limits.
    memory_limiter: null
  receivers:
    jaeger: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus: null
    zipkin: null
    opencensus: 
      endpoint: 0.0.0.0:55678
  service:
    extensions:
      - health_check
    pipelines:
      logs:
        exporters:
          - debug
        processors:
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - debug
        processors:
          - batch
        receivers:
          - otlp
          - opencensus
      traces:
        exporters:
          - debug
        processors:
          - batch
        receivers:
          - otlp