apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |
    replica-read-only yes
    appendonly yes
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: redis-replica
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
      - name: redis
        image: redis:7
        args:
          - "redis-server"
          - "/etc/redis/redis.conf"
          - "--replicaof"
          - "redis-master.redis.svc.cluster.local"
          - "6379"
        ports:
        - containerPort: 6379
          hostPort: 6379
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - name: config
          mountPath: /etc/redis
      volumes:
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf
