apiVersion: v1
kind: Secret
metadata:
  name: apm-server-apm-token
  namespace: observability
  labels:
      apm.k8s.elastic.co/name: apm-server
      common.k8s.elastic.co/type: apm-server
type: Opaque
data:
  secret-token: ZWxhc3RpYw== # base64(elastic)
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: observability
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef: 
    name: kibana
  config:
    secretToken: elastic
    output:
      elasticsearch:
        username: "elastic"
        password: "elastic"
  http:
    tls: 
      selfSignedCertificate:
        disabled: true