apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: observability
spec:
  version: 8.2.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: observability
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest

