apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      opencensus:
        endpoint: 0.0.0.0:55678

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      prometheus:
        endpoint: 0.0.0.0:8889
      otlp:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true

    extensions:
        health_check:
        pprof:
        zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp]
        metrics:
          receivers: [opencensus]
          processors: []
          exporters: [logging, prometheus]