---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
  - apiGroups: ['']
    resources: ['nodes/stats']
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: observability
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.88.0
  mode: daemonset
  hostNetwork: true
  serviceAccount: otel-collector
  env:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  config: 
    exporters:
      debug: {}
      otlp/elastic: 
        endpoint: 'apm-server-apm-http.observability.svc.cluster.local:8200'
        headers:
          Authorization: "Bearer elastic"
        tls:
          insecure: true
          insecure_skip_verify: true
    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check:
        endpoint: 0.0.0.0:13133
    processors:
      batch: {}
      # Default memory limiter configuration for the collector based on k8s resource limits.
    receivers:
      kubeletstats:
          collection_interval: 5s
          auth_type: 'serviceAccount'
          endpoint: '${env:K8S_NODE_NAME}:10250'
          insecure_skip_verify: true
          metric_groups:
            - node
            - pod
            - container
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
        - health_check
      pipelines:
        logs:
          exporters:
            - otlp/elastic
          processors:
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - debug
            - otlp/elastic
          processors:
            - batch
          receivers:
            - otlp
            - kubeletstats
        traces:
          exporters:
            - otlp/elastic
          processors:
            - batch
          receivers:
            - otlp