apiVersion: v1
kind: Namespace
metadata:
  name: loadbalancer
  labels:
    name: loadbalancer
  # annotations:
  #   instrumentation.opentelemetry.io/inject-python: "true"  TODO replace with go injection
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: faas-loadbalancer-daemonset
  namespace: loadbalancer
spec:
  selector:
    matchLabels:
      app: faas-loadbalancer
  template:
    metadata:
      labels:
        app: faas-loadbalancer
    spec:
      containers:
        - name: faas-loadbalancer
          image: localhost/faas-loadbalancer:latest
          ports:
            - containerPort: 8080
              hostPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.nodeName
      hostNetwork: true