# add this to knative
# https://stackoverflow.com/questions/56563425/how-to-communicate-with-daemonset-pod-from-another-pod-in-the-same-node
apiVersion: v1
kind: Namespace
metadata:
  name: loadbalancer
  labels:
    name: loadbalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: faas-loadbalancer-daemonset
  namespace: loadbalancer
spec:
  selector:
    matchLabels:
      app: faas-loadbalancer
  template:
    metadata:
      labels:
        app: faas-loadbalancer
    spec:
      # to enable graceful shutdown
      terminationGracePeriodSeconds: 300
      containers:
        - name: faas-loadbalancer
          image: szaboegon/faas-loadbalancer:latest
          ports:
            - containerPort: 8080
              hostPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 2
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_SERVICE_NAME
              value: "faas-loadbalancer"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability:4317
            - name: METRICS_BACKEND_ADDRESS
              value: http://elasticsearch-es-http.observability.svc.cluster.local:9200