apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
      query:
        base-path: /jaeger
    metricsStorage:
      type: prometheus
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
