apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: streaming_instance
spec:
  strategy: streaming
  streaming:
    options:
      log-level: debug
  ingester:
    maxReplicas: 8
    # resources:
    #   limits:
    #     cpu: 100m
    #     memory: 128Mi
  # storage:
  #   type: elasticsearch
